### ISSUE TITLE
why not update bt

### ISSUE THREAD

**Issue by ElusionPDX** [meta-hub/fivem-target#4]
why make us run two copys of the same script. why not update the main BT git with a pull?

**Comment by meta-hub** [comment]
They simply don't function the same.

**Comment by ElusionPDX** [comment]
Issue is we have scripts that are locked that we cant switch to your edited
bt target. Having two eye systems is kinda dum for us to do.

**Comment by Senlar** [comment]
Request access to edit the script or request that the script author provides fivem-target support.

**Comment by ElusionPDX** [comment]
well trying to update stuff to it and its just crashing clients.  Am i just calling your function wrong ?
![image](https://user-images.githubusercontent.com/19332765/121953577-bc37e680-cd2b-11eb-9d95-d3d9cbb01cb1.png)


```
Citizen.CreateThread(function()
    while true do
        Citizen.Wait(0)
exports["fivem-target"]:AddTargetModel({
    name = "pickrocks",
    label = "Mine rocks",
    icon = "fas fa-dog",
    model = GetHashKey('prop_rock_3_f'),
    interactDist = 1.2,
    onInteract = onInteract,
    options = {
      {
        name = "pickem",
        label = "Mine Rocks"
      }
    },
    vars = {
      whatever = "whatever"
    }
  })
  	end
end)

  onInteract = function(targetName,optionName,vars,entityHit)
  if optionName == "pickem" then
	TriggerEvent("pick:rock")
  end
end
```

**Comment by Senlar** [comment]
That’s usually an issue with the function that is being called. Look at pick:rock as the issue most likely.

**Comment by ElusionPDX** [comment]
Ya event is there, was using it with bt-target fine.

**Comment by JericoFX** [comment]
i think you dont need to call it every frame, just delete the while loop and try it again
