### ISSUE TITLE
Add multiple props by his hash key

### ISSUE THREAD

**Issue by LucasFormiga** [meta-hub/fivem-target#5]
Hey, is there a way to add props by his hash key?

For example: I want to add every chair of the Gabz MRPD to be able to sit using the eye, but instead of binding every chair location I may use an option to just say the chair model and the script do everything for me.

Also: How can I add options to every car, I didn't really understand the Network Entity example 😢

Thank u!

**Comment by JericoFX** [comment]
on the client.lua near the end you have AddTargetModels, pass a table with the hash
